name: CI (with OIDC example)

# This workflow demonstrates two approaches for deployment:
# 1) Use GitHub Secrets with Firebase service account JSON (existing flow)
# 2) Use GCP Workload Identity Federation (OIDC) — recommended for production
#
# Trigger: manual only to avoid duplicate runs with the primary CI.
on:
  workflow_dispatch:

permissions:
  id-token: write # required for OIDC
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build

  # Option A: deploy using stored service account JSON in a secret (fallback)
  deploy-with-secret:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Write service account to disk (from secret)
        env:
          FIREBASE_SA: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SA" > /tmp/firebase-sa.json
          chmod 600 /tmp/firebase-sa.json
      - name: Deploy (service account JSON via ADC)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-sa.json
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          firebase --version
          firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --non-interactive
        # Uses Application Default Credentials via GOOGLE_APPLICATION_CREDENTIALS

  # Option B (recommended): OIDC -> impersonate service account in GCP
  deploy-oidc:
    needs: build
    runs-on: ubuntu-latest
    # Guard until OIDC is configured: enable after setting the WIF provider & service account
    if: github.ref == 'refs/heads/main' && false
    environment: production
    steps:
      - uses: actions/checkout@v4

      # Authenticate to GCP using workload identity federation
      - name: Authenticate to GCP (OIDC)
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID
          service_account: projects/PROJECT_NUMBER/serviceAccounts/SA_NAME@PROJECT_ID.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploy with gcloud/fb (OIDC)
        run: |
          # After OIDC auth and setup-gcloud, ADC is available to Firebase CLI
          gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}
          firebase --version
          firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive

# NOTES:
# - Replace PROJECT_NUMBER, POOL_ID, PROVIDER_ID and SA_NAME@PROJECT_ID with values from your GCP setup.
# - To configure Workload Identity Federation in GCP, follow:
#   https://cloud.google.com/iam/docs/workload-identity-federation
# - After configuring, you do NOT need to store the service account JSON in GitHub.
